name: Deploy to server
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        
      - name: Check repo name variable
        run: echo ${{ github.event.repository.name }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}

      - name: Add to known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "*"
          target: "/home/pi/${{ github.event.repository.name }}_new"

      - name: Stop the server, move files around, install dependencies and run the server again
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pm2 stop ${{ github.event.repository.name }}
            rm -rf ~/${{ github.event.repository.name }}
            cp -r ~/${{ github.event.repository.name }}_new ~/${{ github.event.repository.name }}
            rm -rf ~/${{ github.event.repository.name }}_new
            cd ~/${{ github.event.repository.name }}
            npm install --only=prod
            pm2 start ${{ github.event.repository.name }}
