name: Deploy to server
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout master branch
        uses: actions/checkout@v2
        
      - name: test
        run: echo $GITHUB_WORKSPACE
        
        
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: ${{ secrets.SSH_HOST }}
          
              
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        

      - name: Deploy with scp
        run: scp -r /home/runner/work/HeratBot/HeratBot ${{ secrets.USERNAME }}@${{ secrets.SSH_HOST }}:/home/pi/HeratBot_new
    
      - name: Stop server, move files and run the server
        run: |
          
